database:
  mysql:
    enabled: false
    host: localhost
    port: 3306
    username: root
    password: 12345678
    database: softframework
    poolsize: 10
  redis:
    enabled: false
    host: localhost
    port: 6379
    password: ""
