name: SoftFramework
version: '${project.version}'
main: com.softhub.softframework.BukkitInitializer
api-version: '1.20'
website: https://discord.gg/TERRNC9dhv

libraries:
  - com.zaxxer:HikariCP:5.0.1

authors:
  - sjnu