name: SoftFramework
version: '1.0.2'
main: com.softhub.softframework.BukkitInitializer
api-version: '1.20'
website: https://discord.gg/kk4UQstdY9

libraries:
  - com.zaxxer:HikariCP:5.0.1

authors:
  - minhyeok